# Generated by Django 4.0.6 on 2037-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_image3_product_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=400)),
                ('Reaction', models.CharField(max_length=400)),
                ('Review', models.TextField(blank=True)),
                ('slug', models.TextField()),
                ('date', models.CharField(max_length=400)),
                ('point', models.IntegerField(default=1)),
            ],
        ),
    ]
